### ISSUE TITLE
Pictures in Suits

### ISSUE THREAD

**Issue by space-barry** [project-powerful/making-datasets#1]
There are some issues in the pictures of the president, maybe his right arm is not swinging in any image that is captured in the suit, and it feels like something is odd. Please check it

- [x] Somehow peed on the President's arm
- [x] Take an image if possible
- [ ] touch it (sacrifice of your life)
- [x] Is it there or not
- [x] if there real or face?

**Comment by space-barry** [comment]
It is been a while, but I feel like the President is trying to hide their arm!!

**Comment by space-barry** [comment]
@asgharas what's your status??

**Comment by space-barry** [comment]
That image is encrypted in [here](...)

**Comment by asgharas** [comment]
Intercourse for fun. Are you insane sir?

**Comment by asgharas** [comment]
> @asgharas what's your status??

HWAT?
